"""remove field

Revision ID: 4c864f693169
Revises: 6208f13f8191
Create Date: 2025-03-15 22:55:59.543480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c864f693169'
down_revision: Union[str, None] = '6208f13f8191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraperjobs', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraperjobs', sa.Column('created_at', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
