"""update model relationship

Revision ID: ba10eb3f40d6
Revises: 35533198a709
Create Date: 2025-03-15 21:41:32.801101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ba10eb3f40d6'
down_revision: Union[str, None] = '35533198a709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userjoblink')
    op.add_column('scraperjobs', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'scraperjobs', 'user', ['user_id'], ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scraperjobs', type_='foreignkey')
    op.drop_column('scraperjobs', 'user_id')
    op.create_table('userjoblink',
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scraperjobs.job_id'], name='userjoblink_job_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.username'], name='userjoblink_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'job_id', name='userjoblink_pkey')
    )
    # ### end Alembic commands ###
